services:
  mongo:
    command: ["mongod", "--wiredTigerCacheSizeGB", "0.25"]
    mem_limit: 640m
    cpus: 0.75

  backend:
    build: !reset null
    image: ${BACKEND_IMAGE:-idrisovmarat/lab_back:latest}
    mem_limit: 640m
    cpus: 1.0

  frontend:
    build: !reset null
    image: ${FRONTEND_IMAGE:-idrisovmarat/lab_front:latest}
    ports: !override
      - ${PUBLIC_BIND_ADDRESS:-0.0.0.0}:${PUBLIC_PORT:-80}:8080
    mem_limit: 128m
    cpus: 0.25
